# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demos", "0002_alter_demo_options_alter_demolist_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="demo",
            table="demo",
        ),
        migrations.AlterModelTable(
            name="demolist",
            table="demo_list",
        ),
    ]
