# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studios", "0002_alter_animestudios_options_alter_studio_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="animestudios",
            table="anime_studios",
        ),
        migrations.AlterModelTable(
            name="studio",
            table="studio",
        ),
    ]
