# Generated by Django 4.1.7 on 2023-03-23 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broadcasts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="broadcastlist",
            options={"managed": False},
        ),
    ]
