# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broadcasts", "0002_alter_broadcast_options_alter_broadcastlist_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="broadcast",
            table="broadcast",
        ),
        migrations.AlterModelTable(
            name="broadcastlist",
            table="broadcast_list",
        ),
    ]
