# Generated by Django 4.1.7 on 2023-06-18 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_gender_user_is_manager_user_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
