# Generated by Django 4.1.7 on 2023-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="abc", max_length=150),
        ),
    ]
