# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animes", "0002_alter_anime_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="anime",
            table="anime",
        ),
    ]
