# Generated by Django 4.1.7 on 2023-04-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animes", "0003_alter_anime_table"),
        ("mylists", "0002_alter_mylist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mylist",
            name="animes",
        ),
        migrations.AddField(
            model_name="mylist",
            name="animes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mylists",
                to="animes.anime",
            ),
        ),
    ]
