# Generated by Django 4.1.7 on 2023-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animes", "0003_alter_anime_table"),
        ("mylists", "0003_remove_mylist_animes_mylist_animes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mylist",
            name="animes",
        ),
        migrations.AddField(
            model_name="mylist",
            name="animes",
            field=models.ManyToManyField(related_name="mylists", to="animes.anime"),
        ),
    ]
