# Generated by Django 4.1.7 on 2023-03-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animes", "0003_alter_anime_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "10"),
                            (9, "9"),
                            (8, "8"),
                            (7, "7"),
                            (6, "6"),
                            (5, "5"),
                            (4, "4"),
                            (3, "3"),
                            (2, "2"),
                            (1, "1"),
                        ],
                        default="10",
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="animes.anime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
