# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0002_alter_theme_options_alter_themelist_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="theme",
            table="theme",
        ),
        migrations.AlterModelTable(
            name="themelist",
            table="theme_list",
        ),
    ]
