# Generated by Django 4.1.7 on 2023-03-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0002_alter_source_options_alter_sourcelist_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="source",
            table="source",
        ),
        migrations.AlterModelTable(
            name="sourcelist",
            table="source_list",
        ),
    ]
